name: DiscordUtils
version: '${project.version}'
main: me.rrs.discordutils.DiscordUtils
api-version: '1.13'
authors: [ RRS ]
description: DiscordUtils
website: https://discord.gg/fV4P2yMSgR
folia-supported: true

softdepend:
  - DiscordSRV
  - BedWars1058
  - MBedwars
  - BedWars
  - EssentialsDiscordLink
  - ajLeaderboards
depend:
  - PlaceholderAPI
commands:
  discordutils:
    aliases: du
    usage: /discordutils
    description: Main command for DiscordUtils plugin
  profile:
